//
// Autogenerated by Natalie - Storyboard Generator Script.
// http://blog.krzyzanowskim.com
//

import UIKit

//MARK: - Storyboards
enum Storyboards: String {
    case Main = "Main"
    case ModulesCatalog = "ModulesCatalog"

    private var instance:UIStoryboard {
        return UIStoryboard(name: self.rawValue, bundle: nil)
    }

    func instantiateInitialViewController() -> UIViewController? {
        switch (self) {
        case Main:
            return self.instance.instantiateInitialViewController() as! UINavigationController
        default:
            return self.instance.instantiateInitialViewController() as? UIViewController
        }
    }

    func instantiateViewControllerWithIdentifier(identifier: String) -> UIViewController {
        return self.instance.instantiateViewControllerWithIdentifier(identifier) as! UIViewController
    }
}

//MARK: - SegueKind
enum SegueKind: String, Printable {    
    case Relationship = "relationship" 
    case Show = "show"                 
    case Presentation = "presentation" 
    case Embed = "embed"               
    case Unwind = "unwind"             

    var description: String { return self.rawValue } 
}

//MARK: - SegueProtocol
protocol SegueProtocol {
    var identifier: String { get }
}

//MARK: - UIViewController extension
extension UIViewController {
    class var storyboardIdentifier:String? { return nil }
    func performSegue(segue: SegueProtocol, sender: AnyObject?) {
       performSegueWithIdentifier(segue.identifier, sender: sender)
    }
}


//MARK: - ModulesCatalogView

extension ModulesCatalogView {
    override class var storyboardIdentifier:String? { return "ModulesCatalogView" }
}

